export function defineMineCraftConstants(Blockly) {
    Blockly.Msg =  {
            MINECRAFT_COLUMN: "column",
            MINECRAFT_COLUMN_WIDTH: "width",
            MINECRAFT_COLUMN_HEIGHT: "height",
            MINECRAFT_COLUMN_TYPE: "type",
            MINECRAFT_COLUMN_FILLED: "filled",
            MINECRAFT_PLANE: "plane",
            CATEGORY_CRAFT: "Craft",
            MINECRAFT_FAKE_KEYBOARD_HAT: "fake keyboard hat",
            MINECRAFT_FAKE_KEYBOARD_HAT_PRESSED: "pressed",
            MINECRAFT_FAKE_KEYBOARD_HAT_TOGGLED: "toggled",
            MINECRAFT_SET_BLOCK: "set block",
            MINECRAFT_TYPE: "type",
            MINECRAFT_SET_BLOCKS: "set blocks",
            MINECRAFT_SIZE: "size",
            MINECRAFT_SET_FLOOR: "set floor",
            MINECRAFT_CREATE_DOOR: "create door",
            MINECRAFT_CREATE_DOOR_FACING: "facing",
            MINECRAFT_FACING_NORTH: "north",
            MINECRAFT_FACING_SOUTH: "south",
            MINECRAFT_FACING_EAST: "east",
            MINECRAFT_FACING_WEST: "west",
            MINECRAFT_CREATE_SHAPE: "create shape",
            MINECRAFT_SHAPE_CUBE: "cube",
            MINECRAFT_SHAPE_SPHERE: "sphere",
            MINECRAFT_SHAPE_PYRAMID: "pyramid",
            MINECRAFT_PRIMITIVE_TYPE: "type",
            MINECRAFT_CREATE_SHAPE_POSITION: "position",
            MINECRAFT_PRIMITIVE_SIZE: 'size',
            MINECRAFT_PRIMITIVE_RADIUS: 'radius',
            MINECRAFT_PRIMITIVE_BASE: 'base',
        }
}
